<a href="https://colab.research.google.com/github/erinmr/ATLS-5519/blob/main/Day_7_ER_Submitted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 7 - June 14 

##IP 22 [Lifeguards Problem](http://www.usaco.org/index.php?page=viewproblem2&cpid=784) 
- Pool is open from t=0 to t=1000
- 0<= t <= 1000 
- Number of life guards 1 <= N <= 100. 
- line 1 = N 
- lines 2 - N+1 = time interval ts1, te1 
- Does not need to be continuous coverage 
- Fire the life guard with the most % of overlap 

**Pseudocode Brainstorm:** 
1. Calculate the % overlap for all cows 
2. If row overlap 
  - put cow in the list 
3. Elif find max (% overlap): 
4. Make a class for cows 
5. Data structure for time line and number of cows 
6. Get rid of betsy from structure and then check if empty - skip elif, add 1 

**Pseudocode Round 2** 
1. Input - N cows and list of lists
2. Map cows to time points 
3. Calculate % for each overlap 
  - For each cow: 
  - Cow class:
    - ts - 3 
    - te - 7
    - %o - 1- (len of change interval/(te-ts))
    - interval is a list [3, 4, 5, 6] 
    - change interval [4] 
  


**Final Pseudocode:** 
1. Input number of lifeguards (n)
2. Input start time and end time for each lifeguard (lifeguards)
3. Establish a 0 filled array with N rows and total time columns 
4. Each row is a cow
  - Fill in 1s for each shift 
5. Use numpy delete row to delete the first row
6. Numpy sum, axis = 0 will sum all columns
7. Numpy count non-zero will count all values that aren't 0 giving us the number of shifts covered
9. Set this initial non-zero count to max 
8. In a for loop repeat items 5-8 
9. Compare current non-zero count to max. 
10. If current greater than max, set max = current 
11. After looping through all options, Print max shifts covered 



In [24]:
import numpy as np

N = 3 # number of cows
total_time = 10 # max time length that a shift could span 
shifts = [[5,9],[1,4],[3,7]] #[[134, 203], [186,288], [274,308], [46,138], [373, 451]] # # specified cow shifts
max_shift=0 # intialize max shift length to 0 so that something will always 
total_shift = 0 

#initialize array with a line for each cow 
j=np.zeros((N, total_time)) # more elegant way to inialize the array than creating it by hand 
j = j.astype(int)

#j=np.array([[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0]]) #array for all 

i=0
t=0

for i,s in enumerate(shifts): # building j numpy array 
  #print(i,s)
  for t in range(s[0],s[1]): 
    #print(type(t))
    j[i][t] = 1               #with 1's in spaces from start to end time for each cow row
    #print(j[i][t])

print(j)

#Establish first row delete outside. Test for comparing two arrays 
j_del = np.delete(j,0,0) #delete first row
j_del_sum = np.sum(j_del,0) #Sum all columns 
#print(j_del_sum)
j_del_nonzero = np.count_nonzero(j_del_sum) # count all non-zeros to find the number of shifts covered. 

max_nonzero_shifts = j_del_nonzero #Set max to initial 

for k in range(1,N):
  j_del2 = np.delete(j,k,0) #delete 2nd to Nth row
  j_del2_sum = np.sum(j_del2,0) #sum the columns 
  #print(j_del2_sum)
  j_del2_nonzero = np.count_nonzero(j_del2_sum) #count non-zeros to find number of shifts
  #print(j_del2_nonzero)

  if j_del2_nonzero > max_nonzero_shifts: #compare current shifts to max and if greater set greater equal to current 
    max_nonzero_shifts = j_del2_nonzero
    print('True', max_nonzero_shifts,j_del2_sum)



[[0 0 0 0 0 1 1 1 1 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]]
True 7 [0 1 1 1 0 1 1 1 1 0]



# Impractical Project #23: Ski Course Design

Objective: See http://www.usaco.org/index.php?page=viewproblem2&cpid=376 


Check all ranges to 17 (1-18, , 2-19, 3-20, 4-21, 5-22)

**Pseudocode**
1. Read in hills height 
2. Sort hill height
3. set min_hill_interval = 0 (not sure if this could be hills[0]? 
4. Set max_hill_interval = hills[-1]-17, this is the tallest hill in the set and - 17 gives us our bottom part of the range. 
5. First for loop will create ranges with i to i+17 with the min and max hill interval: 
  - iterate over all the hills and calculate the cost 
  - if the hill is in the range, it's cost will be 0 
  - if hill is less than i then hill cost is (i-hill)^2
  - if hill is greater than i then hill cost is (hill-(i+17))^2
  - sum the hill_cost for this interval 
  - compare the hill_cost to min_cost; if hill_cost < min_cost, then set min_cost = hill_cost 

In [39]:
hills = [50,50,84,22,44,38,0,46,66,22,73,25,92,5,56,13,73,48,32,42,91,3,100,97,8,27,34,73,58,42,80,53,59,55,52,3,30,84,100,31,80,79,11,70,55,64,92,29,77,71,72] #[20, 4, 1, 24, 21] 
hills.sort()
min_hill_interval = 0 #;hills[0]
total_cost = 0
hill_cost = 0
max_hill_interval = hills[-1]-17 # tallest hill - 17 gives the lower bound of the iterations to go through. 
min_cost = 999999 # set min cost to much higher than needed

# print(max_hill_interval)


for i in range(min_hill_interval, max_hill_interval+1): #create intervals 
  #print(f'i is {i}')
  total_cost = 0
  for hill in hills: # Iterate over all hills for each interval 
    if hill in range(i, i+17):
      hill_cost = 0
      #print(f'hill_cost for in range: {hill_cost}')
    elif hill < i: 
      hill_cost = (i-hill)*(i-hill)
      #print(f'hill_cost for less than range: {hill_cost}')
    elif hill > i: 
      hill_cost = (hill-(i+17))*(hill-(i+17))
      #print(f'hill_cost for greater than range: {hill_cost}')
    
    total_cost += hill_cost # sum the total cost
    
  if total_cost < min_cost: #compare the cost   
    min_cost = total_cost  # if total less than min, min = total
  

print(min_cost) #print min cost 


22946
